### ISSUE TITLE
I'm interested in contributing

### ISSUE THREAD

**Issue by theCSEnthusiast** [oldrich-s/musicope#24]
Hello, I'm interested in contributing to your project. Can you tell me a bit about it?

**Comment by Volumie** [comment]
well hey, This is kind of synthesia but it is browser based and what it doesn't have is that it cannot output sound from pc ,That is it requires synthesizer and will not work with the midi keyboards.

**Comment by czb** [comment]
@Volumie  Well it can output the sound if you change a couple of lines of code ;) I made this game purely for me. That is why I implemented only things that I find interesting to me :). But you are welcome to take the game and change it to fit your needs ;)

@abhijeetthecode What is it that you would like to know? :)

**Comment by arretxe** [comment]
Hi!
I was looking for something like this, as I would like to make something similar for an accordion.
My knowledge of coding is very basic but I hope the adaptation will be pretty simple (just changing the graphics and which button needs to be highlighted for each note).
To start with I would like to be able to build the Windows version from the source code myself, to then start editting the code.
Which software would I need for that?

Thanks in advance!!

**Comment by czb** [comment]
I have just reorganised the game a little bit. Try to follow the bullet points on the frontpage: 

https://github.com/musicope/game

Let me know if you cannot make it up and running.

**Comment by arretxe** [comment]
Hi, I have finally taken some time to try it and I got it working!
Now, where should I start to change the graphics of the piano?
I would like to draw an accordion instead

**Comment by czb** [comment]
take a look here:

https://github.com/czb/musicope/tree/master/static/web/game/scene

especially the draw-xxx.ts files ;)
