### ISSUE TITLE
Error's on installing

### ISSUE THREAD

**Issue by ouch67** [oldrich-s/musicope#32]
I'm trying to run this on a raspberry pi so I'm not sure how it will work. but anyway, I'm getting the following erros and am not sure what to do about them.

pi@raspberrypi:~/musicope $ sudo npm install
(node:4901) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.79-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/musicope
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/musicope/npm-debug.log
npm ERR! not ok code 0
pi@raspberrypi:~/musicope $

**Comment by oldrich-s** [comment]
Either there is an issue with dependecies (express, typescript) or with NodeJS. You could try to update `express` and `typescript` to the latest versions (in `package.json`) and see if it helps. You could also try to install Node 10 instead of Node 8.
