### ISSUE TITLE
Can Hardly Load Anything

### ISSUE THREAD

**Issue by GamingMidi** [oldrich-s/musicope#39]
I tried loading a small black midi, only 2k notes.. and it doesn't play it at all, the screen just stays black with the midi name in the corner, Can you try and fix this?

**Comment by tuxutku** [comment]
same issue on Pop!_OS

**Comment by tuxutku** [comment]
I just realised that you will need chrome for web midi (which this app depends on) and its only available on chrome (not even chromium)
