### ISSUE TITLE
The notes are off

### ISSUE THREAD

**Issue by KilThrall** [oldrich-s/musicope#40]
Well, I found 2 problems, I don't know if I made something wrong or if the problem is the program, but if there is any way to fix it please tell.
The first problem is that if there are 2 times the same note play together with little to no time in between, the program doesn't play them.
The second problem is that the notes are played a bit before actually touching the "piano" image, so you have to "predict" when to play a note instead of seing when to do so. 
Sorry if I made any mistakes, I am non-native
Edit: Also after messing around with some configurations something stopped working and now I can't even play it
Edit 2: I couldn't find a solution for the first problem, but I kinda patched the second one by adding a +75 to the piano height in the drawscene file, though it bugs the "wait" function, so it's not a really good solution

**Comment by oldrich-s** [comment]
actually it was made on purpose like that. I had it before like you suggest - ie. you press the note when it touches the piano but it did not work well.

as for the sounds - my piano plays all the notes so i cant comment on that
