### ISSUE TITLE
How is this a "game"?

### ISSUE THREAD

**Issue by francogrex** [oldrich-s/musicope#48]
All it does is play midi files (and by the way the sound is horrible compared to other synthesizers like for example (UMP) by PipiraMine). Is it that primitive or am I missing anything

**Comment by oldrich-s** [comment]
[![Mutable.ai Auto Wiki]([https://img.shields.io/badge/Auto_Wiki-Mutable.ai-blue)]https://wiki.mutable.ai/oldrich-s/musicope](https://img.shields.io/badge/Auto_Wiki-Mutable.ai-blue)%5Dhttps://wiki.mutable.ai/oldrich-s/musicope))

**Comment by AlexeyBeletskiy** [comment]
Hi, @oldrich-s! I faced the same issue as @francogrex. 
Unfortunately, the link above doesn't work. Do you have another link on how to use this app?
Great idea, btw. Looking forward to play this game 👍

**Comment by Zahrun** [comment]
@oldrich-s the link is down
